[baseurl]
url=https://www.zoho.com/
home_url=https://home.zoho.in/home

[locators]
SignIn=Sign In
enteremail=input#login_id
check_email_field=Email address or mobile number
clickNext_btn=button#nextbtn
enterpassword=input#password
signin_btn=button#nextbtn

invalid_email=.fielderror.errorlabel
invalid_pwd_error=.fielderror.errorlabel

#Invalid password
invalid_pass_error_msg=div.fielderror.errorlabel

userProfile=#ztb-profile-image-pre
signOut_btn=#ztb-signout


#CRM Page
CRM_link=.app-nm:has-text('CRM')
create_btn=div#createIcon
Account_optn=Account
Account_name_input_field=#Crm_Accounts_ACCOUNTNAME_LInput
Phone_input_field=#Crm_Accounts_PHONE_LInput
rating_dropdown=[aria-labelledby='Crm_Accounts_RATING_label']
options=Active
street_add_input_field=#Crm_Accounts_BILLINGSTREET_LInput
city_input_field=#Crm_Accounts_BILLINGCITY_LInput
State_input_field=#Crm_Accounts_BILLINGSTATE_LInput
code_input_field=#Crm_Accounts_BILLINGCODE_LInput
country_input_field=[aria-labelledby="Crm_Accounts_BILLINGCOUNTRY_label"]
description_input_field=[aria-labelledby="Crm_Accounts_DESCRIPTION_label"]
Save_btn=#crm_create_savebutn
Account_name=#tc_mouseArea__ACCOUNTNAME